;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Event.Primary.Pushed",NewTagName="Event.Reaction.Pushed")
+GameplayTagRedirects=(OldTagName="Event.Primary",NewTagName="Event.Reaction")
+GameplayTagRedirects=(OldTagName="State.Primary.Stuned",NewTagName="State.Primary.CC")
+GameplayTagRedirects=(OldTagName="State.CC.Electirc",NewTagName="State.CC.Electric")
+GameplayTagList=(Tag="Ability.NPC.Action",DevComment="")
+GameplayTagList=(Tag="Ability.NPC.Action.Grab",DevComment="")
+GameplayTagList=(Tag="Ability.NPC.Action.Push",DevComment="")
+GameplayTagList=(Tag="Ability.NPC.Action.Throw",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Block.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Block.Sprint",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Block.Throw",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Emote",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Revive",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Sprint",DevComment="")
+GameplayTagList=(Tag="Ability.Player.Throw",DevComment="")
+GameplayTagList=(Tag="Ability.Primary.Death",DevComment="")
+GameplayTagList=(Tag="Ability.Primary.Dot",DevComment="")
+GameplayTagList=(Tag="Ability.Primary.Electric",DevComment="")
+GameplayTagList=(Tag="Ability.Primary.electric sh",DevComment="")
+GameplayTagList=(Tag="Ability.Primary.FallDown",DevComment="")
+GameplayTagList=(Tag="Ability.Primary.Fear",DevComment="")
+GameplayTagList=(Tag="Ability.Primary.Grabed",DevComment="")
+GameplayTagList=(Tag="Ability.Primary.Pushed",DevComment="")
+GameplayTagList=(Tag="Ability.Primary.Slow",DevComment="")
+GameplayTagList=(Tag="Ability.Primary.Stuned",DevComment="")
+GameplayTagList=(Tag="Ability.Primary.Taunt",DevComment="")
+GameplayTagList=(Tag="Ability.SmartObject.Computer",DevComment="")
+GameplayTagList=(Tag="Buff.HealthRegen",DevComment="플레이어 체력재생")
+GameplayTagList=(Tag="Buff.Speed",DevComment="플레이어 이동속도 증가")
+GameplayTagList=(Tag="Buff.Strength",DevComment="플레이어 힘 증가")
+GameplayTagList=(Tag="Character.NPC",DevComment="")
+GameplayTagList=(Tag="Character.Player",DevComment="")
+GameplayTagList=(Tag="Data.Amount.Dot",DevComment="")
+GameplayTagList=(Tag="Data.Amount.Slow",DevComment="")
+GameplayTagList=(Tag="Data.Duration.Dot",DevComment="")
+GameplayTagList=(Tag="Data.Duration.Electirc",DevComment="")
+GameplayTagList=(Tag="Data.Duration.Fear",DevComment="")
+GameplayTagList=(Tag="Data.Duration.Slow",DevComment="")
+GameplayTagList=(Tag="Data.Duration.Stun",DevComment="")
+GameplayTagList=(Tag="Data.Duration.Taunt",DevComment="")
+GameplayTagList=(Tag="Event.NPC.Collision",DevComment="")
+GameplayTagList=(Tag="Event.NPC.Collision.End",DevComment="")
+GameplayTagList=(Tag="Event.NPC.Collision.Start",DevComment="")
+GameplayTagList=(Tag="Event.NPC.Hitbox.Hit",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.Death",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.Dot",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.Eletric",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.FallDown",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.Fear",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.Grabbed",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.GrabRelease",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.Pushed",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.Slow",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.Stuned",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.Taunt",DevComment="")
+GameplayTagList=(Tag="Event.Reaction.Thrown",DevComment="")
+GameplayTagList=(Tag="Event.StatusEffect.Stun",DevComment="스턴 상태이상 GA 실행 이벤트")
+GameplayTagList=(Tag="State.CC.Electric",DevComment="")
+GameplayTagList=(Tag="State.CC.FallDown",DevComment="")
+GameplayTagList=(Tag="State.CC.Fear",DevComment="")
+GameplayTagList=(Tag="State.CC.Slow",DevComment="")
+GameplayTagList=(Tag="State.CC.Stuned",DevComment="")
+GameplayTagList=(Tag="State.CC.Taunt",DevComment="")
+GameplayTagList=(Tag="State.Damegeble.Dot",DevComment="")
+GameplayTagList=(Tag="State.ElectricShock",DevComment="감전 상태")
+GameplayTagList=(Tag="State.Held",DevComment="")
+GameplayTagList=(Tag="State.NPC.ActionRunning",DevComment="")
+GameplayTagList=(Tag="State.NPC.Grabbing",DevComment="")
+GameplayTagList=(Tag="State.NPC.Home",DevComment="NPC가 홈 위치로 복귀하는 상태")
+GameplayTagList=(Tag="State.NPC.Patrol",DevComment="")
+GameplayTagList=(Tag="State.NPC.Stay",DevComment="NPC대기상태")
+GameplayTagList=(Tag="State.NPC.Tracking",DevComment="")
+GameplayTagList=(Tag="State.Player.Carrying.Character",DevComment="")
+GameplayTagList=(Tag="State.Player.Carrying.Coop",DevComment="")
+GameplayTagList=(Tag="State.Player.Carrying.Heavy",DevComment="")
+GameplayTagList=(Tag="State.Player.Carrying.Item",DevComment="")
+GameplayTagList=(Tag="State.Player.Dead",DevComment="플레이어 최종 사망 상태")
+GameplayTagList=(Tag="State.Player.Encumbered.Heavy",DevComment="")
+GameplayTagList=(Tag="State.Player.Encumbered.Immobile",DevComment="")
+GameplayTagList=(Tag="State.Player.Encumbered.Overloaded",DevComment="")
+GameplayTagList=(Tag="State.Player.Exhausted",DevComment="")
+GameplayTagList=(Tag="State.Player.Groggy",DevComment="플레이어 1차 다운(그로기) 상태")
+GameplayTagList=(Tag="State.Player.Held",DevComment="")
+GameplayTagList=(Tag="State.Player.HitReaction",DevComment="플레이어 피격/충돌 반응 상태")
+GameplayTagList=(Tag="State.Player.Knockdown",DevComment="플레이어 넉다운 상태")
+GameplayTagList=(Tag="State.Player.Pushing",DevComment="")
+GameplayTagList=(Tag="State.Player.Reviving",DevComment="")
+GameplayTagList=(Tag="State.Primary.CC.Stuned",DevComment="")
+GameplayTagList=(Tag="State.Primary.Grabed",DevComment="")
+GameplayTagList=(Tag="State.Primary.Pushed",DevComment="")
+GameplayTagList=(Tag="State.Stunned",DevComment="스턴/기절 상태")

